### PR TITLE
Feat(): medusa plugin auth

### PR DESCRIPTION
**Pull request by adrien2p**
Enable custom authentication provider such as google, facebook, twitter, etc...

### CODE REVIEW

**Comment by juanzgc** [comment]
Thanks for the Plugin! A lot of people will appreciate it 😄 

I'm having an issue when testing the Google login with Admin, not sure if you came across it:
image

When looking around this is usually because `callbackURL` isn't sent in the Google Strategy with `passport` but that is not the case here since you have set that in the PR correctly. Not sure if this might be an issue with how I've set up Google Auth Credentials? 

image

Admin: `http://localhost:8080`
Medusa Backend: `http://localhost:9000`

**Comment by adrien2p** [comment]
Thanks for testing it man 👌

What ha you configured in your médusa-config?

**Comment by juanzgc** [comment]
```
  {
    resolve: 'medusa-plugin-auth',
    options: {
      google: {
        clientID: GOOGLE_CLIENT_ID,
        clientSecret: GOOGLE_CLIENT_SECRET,
        admin: {
          callbackURL: `${BACKEND_URL}/admin/auth/google/cb`,
          failureRedirect: `${ADMIN_URL}/login`,
          successRedirect: `${ADMIN_URL}/`,
          authPath: '/admin/auth/google',
          authCallbackPath: '/admin/auth/google/cb',
          expiresIn: '24h',
        }
      }
    }
  }
```

Where `BACKEND_URL: http://localhost:9000` and `ADMIN_URL: http://localhost:8080`

**Comment by adrien2p** [comment]
Seams to be right. Might comes from your google configuration

**Comment by juanzgc** [comment]
Conclusion: The `medusa-config` variable was misspelled on my end 😇 . We must pass `callbackUrl` instead of `callbackURL` 😆 

After testing we realized the following updates that could be made to this!
- Set error logging to prevent future spelling mistakes with the config 
- Whitelist allowed Google Auth users. Possibly only allow Login, and new users should be sent an invitation.

Thanks Adrien for all of the help and for this plugin!

**Pull request merged**
