### PR TITLE
feat: add support for strict options

### PR DESCRIPTION
**Pull request by adrien2p**
**What**

Add support for strict options
- strict

When `strict ` is set to `all`, then both admin and store domains will be strict.
When set to `admin` is enabled, then admin domain will be strict.
When set to`store` is enabled, then store domain will be strict.

### CODE REVIEW

**Comment by adrien2p** [comment]
@pevey what do you think of the last commit?

**Comment by adrien2p** [comment]
Ahah my bad, i wanted to add it and completely forgot. none would just be part of the possible values but nothing to change in the code. Thanks 🎉

**Review by quang-ng — COMMENTED** [review]
This feature is extremely beneficial, and I am eagerly anticipating its inclusion in the upcoming release.

**Comment by adrien2p** [comment]
I just need to update the doc and yes it will get out soon 🔥

**Comment by adrien2p** [comment]
I think we should be good @pevey would you like to review it?

**Comment by adrien2p** [comment]
@quang-ng would you like to review the pr before I release please

**Comment by pevey** [comment]
I will forego reviewing since I'm not yet familiar enough with the workings of the plugin.  I plan to implement in a project over the next week.  For now, I will do a yolo and say LGTM!

**Comment by quang-ng** [comment]
> @quang-ng would you like to review the pr before I release please

LGTM @adrien2p I lack the authorization to give my approval for it on Github.

**Pull request merged**
