### PR TITLE
Feature/add steam passport

### PR DESCRIPTION
**Pull request by stephane-segning**
This is a pull request to add Steam support. But some limitations are to be listed:
- This can't work with admin: The current code find users by email & steam don't expose emails
- https://developer.valvesoftware.com/wiki/Steam_Web_API#GetPlayerSummaries_.28v0002.29
- https://steamid.pro/how-to-find-out-someones-steam-email#:~:text=Steam%20never%20discloses%20emails%20of,never%20trust%20third%20party%20services.

### CODE REVIEW

**Comment by adrien2p** [comment]
in medusa, the email is mandatory and a user can't exist without email. I would maybe suggest that we store the identifier in the metadata of the user and have a custom validate callback for the steam strategy. Also, it would mean that the user needs to first register/login with the classic method to gather the email and then will be able to use steam to authenticate wdyt?

**Comment by stephane-segning** [comment]
> I would maybe suggest that we store the identifier in the metadata of the user and have a custom validate callback for the steam strategy.

Meaning we should also make sure the metadata is written at some point? Is it in the scope of this plugin? For reading it, it's simple. But writing it should be easy. What are the solutions for writing metadata?

**Comment by adrien2p** [comment]
You can have a look at the core validator, we are already writing some metadata to store the provider that have been used

**Comment by stephane-segning** [comment]
I saw that already. But for setting it, how it going to happen?

**Comment by adrien2p** [comment]
> I saw that already. But for setting it, how it going to happen?

The problem is that it would work only if it is when the user gets created. I am not sure how to handle this strategy 😓

**Comment by adrien2p** [comment]
> This is it. We can also throw an exception and require the user to implement a custom logic for this case

sounds like the best approach for this specific case

**Comment by adrien2p** [comment]
Yes you can indeed auto generate a random email, but I would prefer that this part stays in the hand on the consumer to be managed.

**Comment by piereligio** [comment]
> Yes you can indeed auto generate a random email, but I would prefer that this part stays in the hand on the consumer to be managed. 

Yeah makes sense. I was thinking of autogenerating it just to make the thing work, and then prompt the user to specify their own one, maybe also from user settings to be changed. In my case emails aren't important (if authentication is managed with steam), because I already customized the front store in such a way that the user can download the content from the website itself, and it's always pretty clear. But yeah it's better if I can also contact users to notify updates and such, so I might still ensure that they insert their email somehow.

**Comment by piereligio** [comment]
> Yes you can indeed auto generate a random email, but I would prefer that this part stays in the hand on the consumer to be managed. 

Yeah makes sense. I was thinking of autogenerating it just to make the thing work, and then prompt the user to specify their own one, maybe also from user settings to be changed. In my case emails aren't important (if authentication is managed with steam), because I already customized the front store in such a way that the user can download the content from the website itself, and it's always pretty clear. But yeah it's better if I can also contact users to notify updates and such, so I might still ensure that they insert their email somehow.

**Comment by adrien2p** [comment]
I believe then that it is a good approach 👍

**Comment by adrien2p** [comment]
What should we do with this pr guys? since it requires a custom validation anyway, it seems it cant be hold by the auth plugin itself right?

**Comment by piereligio** [comment]
> What should we do with this pr guys? since it requires a custom validation anyway, it seems it cant be hold by the auth plugin itself right?

Yeah about steam like I mentioned on the other issue, I had to make it pretty hacky to make it work. It can be useful as a starting point, but can't be in the plugin in this way, imo. Because of the email thing of course

**Comment by piereligio** [comment]
EDIT: it solved by itself, after 15 hours of downtime. Aaargh.

Hey @stephane-segning , thanks again for this plugin, I had to do some touches on it but I am still using it and was working fine.
Sorry for the tag, it's that there is a urgent issue on this now, because of some Steam changes.
It's being discussed here https://steamcommunity.com/discussions/forum/1/601896133034253200/?ctp=2
, mainly two "solutions" are being talked about:
1. "
'Origin' : ['https://steamcommunity.com'](http://'https//steamcommunity.com'),
'Referer' : ['https://steamcommunity.com/'](http://'https//steamcommunity.com/')
after adding these headers to the post request to steam, everything works again"
2. "
Yeah it's broken. Oddly enough if you change the openid back end to use GET requests instead of POST it works. Post returns HTTP 503."

Problem is, I already have GET requests, in the route builder, and I tried applying the first solution in many parts of the code of the plugin. The error I am facing is:
"InternalOpenIDError: Failed to verify assertion"
Can you help me to identify where I actually need to make these edits for trying them? 
I spent the whole night trying to fix this without solution, would be very helpful, thanks in advance.

**Pull request closed without merging**
