### PR TITLE
fix email scope not returning from facebook

### PR DESCRIPTION
**Pull request by edihasaj**

### CODE REVIEW

**Comment by adrien2p** [comment]
Hey man, thanks a lot, did you test it and it works?

**Comment by edihasaj** [comment]
Yeah this works, but there is the issue with 401 again (seems like the changes are not in github only on npm) 401 for google and facebook so far.

**Comment by adrien2p** [comment]
Did you pull the changes on main before creating the branch?

**Comment by edihasaj** [comment]
Yeah I checked multiple times...

**Comment by adrien2p** [comment]
could you re pull main and rebase on your branch and let me know 👍

**Comment by edihasaj** [comment]
Yes if course 🙏

**Comment by adrien2p** [comment]
Is it better now?

**Comment by edihasaj** [comment]
I'm gonna have to check it after 2 hours, because I'm still out 🥴

**Comment by edihasaj** [comment]
I checked the code you commited and it looks good 👍

**Pull request merged**
